export const allPapaItems = [
  'Lunch Special House Basil Prawn',
  'Lunch Special Sweet & Sour Prawn',
  'Lunch Special Black Bean Fish Filet',
  'Lunch Special Hunam Fish Filet',
  'Lunch Special Mongolian Beef',
  'Lunch Special Broccoli Beef',
  'Lunch Special House Basil Chicken',
  'Lunch Special General Tsao Chicken',
  'Lunch Special Orange Chicken',
  'Lunch Special Sweet & Sour Chicken',
  'Lunch Special Hunam Pork',
  'Lunch Special Sweet & Sour Pork',
  'Lunch Special Mapo Tofu',
  'Lunch Special Dry Cooked String Bean',
  'Lunch Special Garlic Broccoli',
  'Lunch Special Salt & Pepper Fish',
  'Lunch Special Salt & Pepper Pork Chop',
  'Lunch Special Vegetable Delight',
  'Lunch Special Mango Chicken',
  'Lunch Special Mango Beef',
  'Tai(Tender Beef Meat)',
  'Pho Bo Vien(Meat Ball)',
  'Pho Dac Biet (Combo)',
  'Chicken Pho (w.Half Egg)',
  'Stewed Tenderloin Noodle Soup',
  'Seafood Pho',
  'Vegetables Pho',
  'House Wonton Soup',
  'Crab Meat Wonton Soup',
  'West Lake Beef Soup',
  'Hot & Sour Soup(No Meat)',
  'Vegetable Tofu Soup',
  'Egg Flower Soup(No Meat)',
  'Grill Chicken RicePlate',
  'Grill Chicken AlaCarte',
  'Grill Pork Chop RicePlate',
  'Grill Pork Chop AlaCarte',
  'Grill Sweet Kebab(Pork) RicePlate',
  'Grill Sweet Kebab(Pork) AlaCarte',
  'Grill Combo(Prawn & Sweet Pork) RicePlate',
  'Grill Combo(Prawn & Sweet Pork) AlaCarte',
  'Grill WhoIe Squid RicePlate',
  'Grill WhoIe Squid AlaCarte',
  'BBQ Beef Short Rib RicePlate',
  'BBQ Beef Short Rib AlaCarte',
  'Shrimp Dumpling(4)',
  'Siu Mai(4)',
  'Steam Pork Bun(4)',
  'ShangHai Dumpling(4)',
  'Steam Bun w.Vietnamese Pork Chop(2)',
  'Vegetable Spring Roll(4)',
  'Cream Cheese Puff (6)',
  'Fried Wonton(Shrimp)(5)',
  'Pot Stickers(5)',
  'Vietnamese Sugar Cane Fried Prawn(2)',
  'PaPa\'s Special Chicken Wings(6)',
  'Vietnamese Style Fried Egg Roll(4)',
  'Vegetable Pot Stickers(5)',
  'Salt & Prpper Caramali',
  'Fried Prawn(6)',
  'Fried Rice Chicken',
  'Fried Rice Pork',
  'Fried Rice VegetabIe',
  'Fried Rice Shrimp',
  'Fried Rice Beef',
  'Fried Rice Combe',
  'Pineapple Prawn Fried Rice',
  'Crab Meat Vegetable Fried Fice',
  'Brown Rice',
  'White Rice',
  'Chow Mein Chicken',
  'Chow Mein Pork',
  'Chow Mein VegetabIe',
  'Chow Mein Shrimp',
  'Chow Mein Beef',
  'Chow Mein Combe',
  'Chow Fun Chicken',
  'Chow Fun Pork',
  'Chow Fun VegetabIe',
  'Chow Fun Shrimp',
  'Chow Fun Beef',
  'Chow Fun Combe',
  'Steak Chow Udon',
  'Golden Prawn Garlic Noodle',
  'Lemongrass Beef Garlic Noodle',
  'Zhajiang Noodles',
  'Pan fried noodles Chicken',
  'Pan fried noodles Pork',
  'Pan fried noodles Shrimp',
  'Pan fried noodles VegetabIe',
  'Pan fried noodles Beef',
  'Pan fried noodles Combe',
  'Pan fried noodles Seafood',
  'Mongolian Beef Chow Mein',
  'Seafood Chow Mein',
  'Seafood Chow Fun',
  'Saefood Noodle Soup',
  'Steak Chow Udon',
  'Lemongrass Chicken Garlic Noodle',
  'Mongolian chicken chow mein',
  'Beef Chow Fun w.Sauce',
  'Dry Cooked Meiji Prawn (w.Shell)',
  'Golden Jinsa Prawns',
  'Creamy Honey Prawns w.Sesame',
  'Dry Fried Garlic Spareribs',
  'Salt & Pepper Pork Chop',
  'Haight Stewed Spareribs',
  'Black Pepper Steak',
  'Stewed Beef Tenderloin Pot',
  'Salt & Pepper Fish Filet',
  'Manderin Fried Chicken',
  'Manderin Chicken Wings(10)',
  'Speical Beef Short Rib Pot',
  'Oxtail Pot',
  'Fresh Vietnamese Shrimp Roll(2)',
  'Fresh Vietnamese Grill Pork Roll(2)',
  'Papaya Shrimp Salad',
  'House Chicken Salad',
  'Mango Chicken Salad',
  'Mongolian Beef',
  'Broccoli Beef',
  'Basil Chicken',
  'General Tsao Chicken',
  'Orange Chicken',
  'Sweet & Sour Chicken',
  'Sweet & Sour Pork',
  'Szechuan Prawn',
  'Sweet & Sour Prawn',
  'Hunam Fish Filet',
  'Dry Cooked String Bean',
  'Mapo Tofu(Soft)',
  'Szechuan Eggplant',
  'Garlic Broccoli',
  'Vegetable Delight',
  'Mango Chicken',
  'Mango Beef',
  'Eggplant Tofu',
  'Lemongrass String Bean Chicken',
  'Coke',
  '7UP',
  'Diet Coke',
  'Jarritos Lime',
  'Jarritos Punch',
  'Sunny D',
  'THAI TEA',
  'ICE COFFEE',
  'Sparking Water',
  'Fanta',
  'Apple Juice',
  'Orange Juice',
  'Fried Rice(Tray)',
  'Beef Fried Rice(Tray)',
  'Shrimp Fried Rice(Tray)',
  'Chow Mein(Tray)',
  'Beef Chow Mein(Tray)',
  'Shrimp Chow Mein(Tray)',
  'General Tso\'s Chicken(Tray)',
  'Sweet & Sour Chicken(Tray)',
  'House Basil Chicken(Tray)',
  'Orange Beef(Tray)',
  'Sweet & Sour Shrimp(Tray)'
];

// some item names are not intuitive, this is a dic that translates intuitive names to names in POS system
export const itemNameTranslator = {
  'Lunch Special House Basil Prawn': 'House Basil Prawn w.Rice',
  'Lunch Special Sweet & Sour Prawn': 'Sweet & Sour Prawn w.Rice',
  'Lunch Special Black Bean Fish Filet': 'Black Bean Fish Filet w.Rice',
  'Lunch Special Hunam Fish Filet': 'Hunam Fish Filet w.Rice',
  'Lunch Special Mongolian Beef': 'Mongolian Beef w.Rice',
  'Lunch Special Broccoli Beef': 'Broccoli Beef w.Rice',
  'Lunch Special House Basil Chicken': 'House Basil Chicken w.Rice',
  'Lunch Special General Tsao Chicken': 'General Tsao Chicken w.Rice',
  'Lunch Special Orange Chicken': 'Orange Chicken w.Rice',
  'Lunch Special Sweet & Sour Chicken': 'Sweet & Sour Chicken w.Rice',
  'Lunch Special Hunam Pork': 'Hunam Pork w.Rice',
  'Lunch Special Sweet & Sour Pork': 'Sweet & Sour Pork w.Rice',
  'Lunch Special Mapo Tofu': 'Mapo Tofu w.Rice',
  'Lunch Special Dry Cooked String Bean': 'Dry Cooked String Bean w.Rice',
  'Lunch Special Garlic Broccoli': 'Garlic Broccoli w.Rice',
  'Lunch Special Salt & Pepper Fish': 'Salt & Pepper Fish w.Rice',
  'Lunch Special Salt & Pepper Pork Chop': 'Lunch Special Salt & Pepper Pork Chop',
  'Lunch Special Vegetable Delight': 'Vegetable Delight w.Rice',
  'Lunch Special Mango Chicken': 'Mango Chicken W.Rice',
  'Lunch Special Mango Beef': 'Mango Beef W.Beef ',
  'Seafood Pho': '海鲜Pho'
};
